### ISSUE TITLE
Windows and chrome now detects it as a virus

### ISSUE THREAD

**Issue by Rizzbert** [ShadowWhisperer/Remove-MS-Edge#40]
![Screenshot 2023-12-18 191824](https://github.com/ShadowWhisperer/Remove-MS-Edge/assets/154227686/2299e491-7a1c-4883-bffd-2209f10b3e5a)
![Screenshot 2023-12-18 191940](https://github.com/ShadowWhisperer/Remove-MS-Edge/assets/154227686/3def9a07-3736-4a68-af32-cf22a1e77b68)

**Comment by FadeMind** [comment]
False Positive

**Comment by ShadowWhisperer** [comment]
Unable to reproduce, but it wouldn't shock me if Microsoft tries to "ban" this tool. I haven't seen any other antivirus software flag it... yet.

Hiding the PowerShell popup, and getting admin permissions to run, are seen as malicious. [VirusTotal](https://www.virustotal.com/gui/file/b6fab3f62e29a08e0ca648b84a99e8144e80e320c626175e995d9b1ac78d7b1f/detection)

If you don't trust it, build it from [Source](https://github.com/ShadowWhisperer/Remove-MS-Edge/tree/main/_Source)

**Comment by Rizzbert** [comment]
oh i was just letting you know that's all.

**Comment by ShadowWhisperer** [comment]
I've been trying to reduce the number of false detentions since this changed from a batch script to an .exe https://github.com/ShadowWhisperer/Remove-MS-Edge/issues/11

Not much has changed from [Here](https://www.virustotal.com/gui/file/e3006700b674ae57c05b090307778e4e85bef116c9da74b1ec1fded8a671a3d2) to [Here](https://www.virustotal.com/gui/file/a9272268e017eced810788b465dd4ce90e4b58e9500a84b382956146b3ff07d3), but detection count went from **5** to **37** (Edge-Only)

😄
