### ISSUE TITLE
Flagged by Windows Defender

### ISSUE THREAD

**Issue by Zephiii** [ShadowWhisperer/Remove-MS-Edge#43]
The recent windows 10 update now flags the app as a Wacatac.

**Comment by ShadowWhisperer** [comment]
Since it appears yall don't know how to read closed issues, or the README. this will remain open.

**It is a false positive**. I have reported it to Microsoft as such.


https://github.com/ShadowWhisperer/Remove-MS-Edge/issues/11
https://github.com/ShadowWhisperer/Remove-MS-Edge/issues/41
https://github.com/ShadowWhisperer/Remove-MS-Edge/issues/40
https://github.com/ShadowWhisperer/Remove-MS-Edge/issues/42

**Comment by FadeMind** [comment]
@ShadowWhisperer  simply add Report from Virus Total and info about false posotives from Windows Defender to readme with references to issues reported here. Regards

**Comment by Zenphia** [comment]
> Since it appears yall don't know how to read closed issues, or the README. this will remain open.

Way to be arrogant. Maybe you should've just said "hey this is a common topic" instead of indirectly flaming me over something I completely forgot to do.

**Comment by ShadowWhisperer** [comment]
Re-opened, to prevent more people from opening the same topic, again.
My response wasn't directed are just you. If you're going to start name calling, _annoyed_ would be the correct word.

![Capture](https://github.com/ShadowWhisperer/Remove-MS-Edge/assets/61057625/309ce0ed-5b20-4210-a89d-d4be1605e3f9)

**Comment by ShadowWhisperer** [comment]
![Capture](https://github.com/ShadowWhisperer/Remove-MS-Edge/assets/61057625/d828a78a-d1fb-4ecb-898c-e420153d6ba6)

**Comment by ShadowWhisperer** [comment]
Analysis Completed
 
 ![Capture](https://github.com/ShadowWhisperer/Remove-MS-Edge/assets/61057625/3533be85-0039-47ff-af07-aa96fefc3e2f)
