### ISSUE TITLE
All files were reported as malicious and deleted.

### ISSUE THREAD

**Issue by Maxwellads** [ShadowWhisperer/Remove-MS-Edge#45]
As you might have already aware of, these files no longer exists on github usercontent anymore, now they are all 404s. Before that, Chrome would detect it as malicious and won't allow downloading (no way no how). I wonder the reason as this tool had really been very useful, and hope that it would be back soon.

**Comment by ShadowWhisperer** [comment]
You are getting a 404 error on GitHub? Strange, just tested and they all downloaded. I see more users have starred this, since this issue was opened. I haven't been able to get Chrome to block it either. (It never has, for me) I have not found any where to report false blocks with Google. Only "Phishing" URLs.

It took Microsoft a long time to allow it.
![300611241-3533be85-0039-47ff-af07-aa96fefc3e2f](https://github.com/ShadowWhisperer/Remove-MS-Edge/assets/61057625/1e1e9840-a719-4cd3-8f36-1025765bb192)

I may have to upload these in a .zip format as well. Try the link below.
Password: SW

[Remove-Edge.zip](https://github.com/ShadowWhisperer/Remove-MS-Edge/files/14112767/Remove-Edge.zip)

**Comment by Maxwellads** [comment]
This link goes to [https://raw.githubusercontent.com/ShadowWhisperer/Remove-MS-Edge/main/Remove-Edge.exe](link) 404 for me, see the image below:

![image](https://github.com/ShadowWhisperer/Remove-MS-Edge/assets/95039679/46727402-4152-4c4e-96ff-cd4729690bc1)

The latter link you posted above is available for download.

**Comment by Maxwellads** [comment]
> This [Link](https://raw.githubusercontent.com/ShadowWhisperer/Remove-MS-Edge/main/Remove-Edge.exe) goes to 404 for me, see the image below:
> 
> ![image](https://private-user-images.githubusercontent.com/95039679/301377908-46727402-4152-4c4e-96ff-cd4729690bc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NjAyMDksIm5iZiI6MTcwNjc1OTkwOSwicGF0aCI6Ii85NTAzOTY3OS8zMDEzNzc5MDgtNDY3Mjc0MDItNDE1Mi00YzRlLTk2ZmYtY2Q0NzI5NjkwYmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDAzNTgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlMDk4ODdlYTJjOWQ2YzUzOWFiYzA4ZTE4ZTczNWMyZTFlYjliMGRlODY4YzAwYzJhY2Y5NWFhNDBhNjNiNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RL86AXSaKpkDvP9vi6ld5NTYJyOo4fnSo-4bWvstEPI)
> 
> The latter link you posted above is available for download.

Okay sorry for distrubing. I just lookuped on the domain of raw.githubusercontent.com on my computer and my DNS gets it to 0.0.0.0. Nice, a normal day in China.
