### ISSUE TITLE
Windows Update Fails and Rolls Back After Uninstalling Edge, Error Code 0x800f0922

### ISSUE THREAD

**Issue by CloudBank-3055** [ShadowWhisperer/Remove-MS-Edge#63]
Description:
After uninstalling Edge, Windows Update fails and rolls back with error code 0x800f0922. The following CBS log files may be helpful for troubleshooting.
[CbsPersist_20240820074001.zip](https://github.com/user-attachments/files/16671322/CbsPersist_20240820074001.zip)

Environment:
版本	Windows 10 企业版 LTSC
版本号	21H2
安装日期	‎2024/‎7/‎15
操作系统内部版本	19044.4780
体验	Windows Feature Experience Pack 1000.19060.1000.0

Steps to Reproduce:
1. Uninstall Edge with this tool.
2. Attempt to run Windows Update by installing the monthly Cumulative Update, such as KB5041580.
3. Update fails and rolls back, displaying error code 0x800f0922.
4. Reinstall Edge and run Windows Update again. This time, the update succeeds without rollback.

Expected Behavior:
Windows Update should complete successfully without errors.
Alternatively, a  notification could be added in the tool: "If Windows Update fails with error code 0x800f0922, please try to reinstall Edge."

**Comment by ShadowWhisperer** [comment]
It does that from time to time

> - Removing Edge may cause update failure loop. 
  Install Edge, install all Windows updates, then remove Edge

**Comment by yonoff** [comment]
Hi, I had the same issue with Windows 10 September 2024 Update LCU - KB5043064 (OS Build 19045.4894).
After rebooting, the message "We couldn't complete the updates , undoing changes" appeared, and the build number remained August - 19045.4780
Reinstalling Edge (I used the Enterprise package) did not solve the problem.
I tried running the _sfc /scannow_ and _dism .... /restorehealth_ commands, and also tried manually installing the MSU file - nothing helped.
The only thing that allowed me to install the update was rebooting into WinRe and applying the MSU file into an offline image using below DISM command:
_dism /Image:C: /Add-Package /PackagePath:"D:\temp\windows10.0-kb5043064-x64.msu" /ScratchDir:"D:\temp\msu"_
The command first quickly ran to 100%, hung at the end and gave an error that the package was not installed. 
However, after rebooting into Windows, the build number was already displayed as September LCU - 19045.4894, and checking for updates showed that all the latest updates were installed.
I really hope that the next update will be installed without problems in the usual way.

**Comment by smanross** [comment]
Just a note on this behavior:

This seems to happen if you use Bye Bye Edge, and the C:\Program files (x86)\Microsoft\Edge directory exists...

** If you are using an x86 version of Windows, then the "Program Files\Microsoft\Edge" directory would be where you need to look instead of Program Files (x86).

It happened to me as well, but ever since I also removed the Edge folder, everything has been updating correctly.  This information was found on the web, but I cant remember where now..  :)

HTH

Maybe the readme could bet updated? in addition to making the program also rename or remove that folder so that Windows updates process correctly???  :)

P.S. all my testing has been down on WIndows 10 Professional

Steven

**Comment by ShadowWhisperer** [comment]
Problem with deleting `C:\Program files (x86)\Microsoft\Edge\` - It is required for WebView to function.   
`C:\Program Files (x86)\Microsoft\EdgeWebView\Application\`

It is in the Readme  *In red
